name: FreeOp
version: '${project.version}'
main: net.txsla.freeop.FreeOp
api-version: '1.21'

permissions :
  op.all:
    description: "This is a permission node"
    default-permission: true
    default: true

commands:
  op:
    description: "Gives operator to the player"
    usage: "/op <arg>"
    aliases: [operator]
    permission: op.all
    permission-message: "You do not have permission to use this command!"
  gmc:
    description: "creative mode"
    usage: "/gmc"
    aliases: [ creative ]
    permission: op.all
    permission-message: "You do not have permission to use this command!"
  gms:
    description: "survival mode"
    usage: "/gms"
    aliases: [ survival ]
    permission: op.all
    permission-message: "You do not have permission to use this command!"
  spectator:
    description: "spectator mode"
    usage: "/spectate"
    aliases: []
    permission: op.all
    permission-message: "You do not have permission to use this command!"
  adventure:
    description: "adventure mode"
    usage: "/adventure"
    aliases: [adventure]
    permission: op.all
    permission-message: "You do not have permission to use this command!"